# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 858991874d671fe8bc9bd0674570a0ae7a11d6226f9e3722f244d9d5e860d9d7bda590e2e2755f8844ff13602cf7d6199995ac36bbb96248337e2bf78e8faa39

test:
  secret_key_base: e6722eed131278b9367ba519dac91003cfe6781155e388cb8191654aef13a802ca19ffec181c545d53609e72207559a7ad0d0a5c9471447d8d2faaf47d55be6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
